### PR TITLE
Release 0.11.0

### PR DESCRIPTION
**Pull request by dcoles**
I think it's about time we cut a new release (we're about 6 months behind the upstream [flipperzero-firmware](https://github.com/flipperdevices/flipperzero-firmware) project).

I'm not opposed to doing smaller point releases for new features while still maintaining the same SDK compatibility.

### CODE REVIEW

**Comment by str4d** [comment]
I see you've ACKed #74; do you want to include it in this release (merging that PR before this one), or leave it to after?

**Review by str4d — APPROVED** [review]
ACK; the changes for the release look correct (I checked against prior release commits).

**Comment by dcoles** [comment]
> I see you've ACKed #74; do you want to include it in this release (merging that PR before this one), or leave it to after (in which case I'll need to rebase it after this PR merges, to alter the correct part of the changelog)?

Sure. Let's get that it. It's easy enough to rebase this branch prior to merging/tagging.

**Review by JarvisCraft — APPROVED** [review]

**Comment by str4d** [comment]
> > I see you've ACKed #74; do you want to include it in this release (merging that PR before this one), or leave it to after (in which case I'll need to rebase it after this PR merges, to alter the correct part of the changelog)?
> 
> Sure. Let's get that it. It's easy enough to rebase this branch prior to merging/tagging.

I merged #74 yesterday. I _think_ it's technically not necessary to rebase this PR as long as the release is done from the `main` branch post-merge, but probably safer to rebase it.

**Comment by str4d** [comment]
It would be nice to get #92 in as well, but I won't have time to review it before the weekend.

**Comment by dcoles** [comment]
Tagged [v0.11.0](https://github.com/flipperzero-rs/flipperzero/tree/v0.11.0) and [released on crates.io](https://crates.io/crates/flipperzero/0.11.0).

**Pull request merged**
