### PR TITLE
ci: enable automatic SDK Update PR creation

### PR DESCRIPTION
**Pull request by JarvisCraft**
# Description

This adds a new manual GitHub Action task capable of updating SDK version and creating a PR with the change.

This also pins dependency versions using `pinact` (which is supported by Dependabot) to ensure security.

# Notes

This is built on top of #151

### CODE REVIEW

**Comment by JarvisCraft** [comment]
@dcoles, hi there! Could you please allow the creation of pull requests by GitHub Actions as [suggested][1] on SO?

[1]: https://stackoverflow.com/a/73155199/6277184

**Comment by dcoles** [comment]
> @dcoles, hi there! Could you please allow the creation of pull requests by GitHub Actions as [suggested](https://stackoverflow.com/a/73155199/6277184) on SO?

Done!

**Review by dcoles — APPROVED** [review]

**Comment by JarvisCraft** [comment]
@dcoles, one more admin action needed.

Could you please add `flipperzero-rs/maintainers` team to this repository as suggested [here][1] so that they can be used when creating a PR. This seems to be the only remaining [blocker][2].

[1]: https://github.com/cli/cli/issues/6395#issuecomment-2021393144
[2]: https://github.com/flipperzero-rs/flipperzero/actions/runs/10404871936/job/28814316234

**Comment by JarvisCraft** [comment]
@dcoles, lightly pinging you on the [previous comment][1] :)

[1]: https://github.com/flipperzero-rs/flipperzero/pull/152#issuecomment-2291327555

**Comment by dcoles** [comment]
Sorry @JarvisCraft. I missed the notification GitHub notification it seems.

The `flipperzero-rs/maintainers` team already has `maintain` access on this repository (I believe that `maintain` is a superset of `read`), so it might be some other issue at hand.

Here's what I currently see on the https://github.com/flipperzero-rs/flipperzero/settings/access page:
image

**Comment by JarvisCraft** [comment]
My apologies, I've forgotten about the mention :D

Since the reviewer parameter seems to be broken, merging this now with it skipped

**Pull request merged**
